# Base kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: echo

resources:
  - foo-deployment.yaml
  - bar-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: echo-service
