apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-bar
  namespace: echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-bar
  template:
    metadata:
      labels:
        app: echo-bar
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo:1.0
          args:
            - "-text=bar"
          ports:
            - containerPort: 5678
          readinessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: echo-bar
  namespace: echo
spec:
  selector:
    app: echo-bar
  ports:
    - port: 80
      targetPort: 5678
      protocol: TCP
