apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-foo
  namespace: echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-foo
  template:
    metadata:
      labels:
        app: echo-foo
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo:1.0
          args:
            - "-text=foo"
          ports:
            - containerPort: 5678
          readinessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: echo-foo
  namespace: echo
spec:
  selector:
    app: echo-foo
  ports:
    - port: 80
      targetPort: 5678
      protocol: TCP
